// <auto-generated />
namespace ProjetoModeloDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DaCadastroadicionadonoProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DaCadastroadicionadonoProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191637303_DaCadastro adicionado no Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
